
classdef KinovaPose < ros.Message
    %KinovaPose MATLAB implementation of kinova_msgs/KinovaPose
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'kinova_msgs/KinovaPose' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'df138c10687e9433a02933f69a1156e0' % The MD5 Checksum of the message definition
        PropertyList = { 'X' 'Y' 'Z' 'ThetaX' 'ThetaY' 'ThetaZ' } % List of non-constant message properties
        ROSPropertyList = { 'x' 'y' 'z' 'ThetaX' 'ThetaY' 'ThetaZ' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        X
        Y
        Z
        ThetaX
        ThetaY
        ThetaZ
    end
    methods
        function set.X(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'KinovaPose', 'X');
            obj.X = single(val);
        end
        function set.Y(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'KinovaPose', 'Y');
            obj.Y = single(val);
        end
        function set.Z(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'KinovaPose', 'Z');
            obj.Z = single(val);
        end
        function set.ThetaX(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'KinovaPose', 'ThetaX');
            obj.ThetaX = single(val);
        end
        function set.ThetaY(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'KinovaPose', 'ThetaY');
            obj.ThetaY = single(val);
        end
        function set.ThetaZ(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'KinovaPose', 'ThetaZ');
            obj.ThetaZ = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.kinova_msgs.KinovaPose.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.kinova_msgs.KinovaPose(strObj);
        end
    end
end
