// Generated by gencpp from file kinova_msgs/KinovaPose.msg
// DO NOT EDIT!


#ifndef KINOVA_MSGS_MESSAGE_KINOVAPOSE_H
#define KINOVA_MSGS_MESSAGE_KINOVAPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kinova_msgs
{
template <class ContainerAllocator>
struct KinovaPose_
{
  typedef KinovaPose_<ContainerAllocator> Type;

  KinovaPose_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , ThetaX(0.0)
    , ThetaY(0.0)
    , ThetaZ(0.0)  {
    }
  KinovaPose_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , ThetaX(0.0)
    , ThetaY(0.0)
    , ThetaZ(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _ThetaX_type;
  _ThetaX_type ThetaX;

   typedef float _ThetaY_type;
  _ThetaY_type ThetaY;

   typedef float _ThetaZ_type;
  _ThetaZ_type ThetaZ;





  typedef boost::shared_ptr< ::kinova_msgs::KinovaPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinova_msgs::KinovaPose_<ContainerAllocator> const> ConstPtr;

}; // struct KinovaPose_

typedef ::kinova_msgs::KinovaPose_<std::allocator<void> > KinovaPose;

typedef boost::shared_ptr< ::kinova_msgs::KinovaPose > KinovaPosePtr;
typedef boost::shared_ptr< ::kinova_msgs::KinovaPose const> KinovaPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinova_msgs::KinovaPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinova_msgs::KinovaPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kinova_msgs::KinovaPose_<ContainerAllocator1> & lhs, const ::kinova_msgs::KinovaPose_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.ThetaX == rhs.ThetaX &&
    lhs.ThetaY == rhs.ThetaY &&
    lhs.ThetaZ == rhs.ThetaZ;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kinova_msgs::KinovaPose_<ContainerAllocator1> & lhs, const ::kinova_msgs::KinovaPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kinova_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kinova_msgs::KinovaPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinova_msgs::KinovaPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinova_msgs::KinovaPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinova_msgs::KinovaPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinova_msgs::KinovaPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinova_msgs::KinovaPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinova_msgs::KinovaPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "df138c10687e9433a02933f69a1156e0";
  }

  static const char* value(const ::kinova_msgs::KinovaPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdf138c10687e9433ULL;
  static const uint64_t static_value2 = 0xa02933f69a1156e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::kinova_msgs::KinovaPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinova_msgs/KinovaPose";
  }

  static const char* value(const ::kinova_msgs::KinovaPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinova_msgs::KinovaPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 ThetaX\n"
"float32 ThetaY\n"
"float32 ThetaZ\n"
;
  }

  static const char* value(const ::kinova_msgs::KinovaPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinova_msgs::KinovaPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.ThetaX);
      stream.next(m.ThetaY);
      stream.next(m.ThetaZ);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KinovaPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinova_msgs::KinovaPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinova_msgs::KinovaPose_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "ThetaX: ";
    Printer<float>::stream(s, indent + "  ", v.ThetaX);
    s << indent << "ThetaY: ";
    Printer<float>::stream(s, indent + "  ", v.ThetaY);
    s << indent << "ThetaZ: ";
    Printer<float>::stream(s, indent + "  ", v.ThetaZ);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINOVA_MSGS_MESSAGE_KINOVAPOSE_H
